bugfix - return of town
dfridrich/Ares pull request #16
Opened 2017-03-19 14:22 UTC by petrparolek

špatné zobrazení města, pokud není městská část

2017-03-21 06:03 UTC, dfridrich commented
Ahoj, díky za PR. Vidím, že Travis v PHP 7 skončil chybou. Kouknul bys na to?

2017-03-23 13:07 UTC, petrparolek commented
Koukám na to, je tam potíž s jiným namespace u PHPUnit

2017-03-24 08:10 UTC, dfridrich commented
@petrparolek Super, diky moc. Jdu to mergnout 😋

2017-03-24 08:13 UTC, dfridrich requested changes

2017-03-24 08:13 UTC, dfridrich commented on src/Ares.php
> +            $cacheDir = '../temp';
Proc odsud zmizel `sys_get_temp_dir()`? Kazdy nemusi mit slozku `../temp`.

2017-03-24 10:22 UTC, petrparolek commented on src/Ares.php
> +            $cacheDir = '../temp';
nebylo by lepší tuto knihovnu převést na extension a použít temp z Nette aplikace konfigurace?

2017-03-28 11:49 UTC, dfridrich commented on src/Ares.php
> +            $cacheDir = '../temp';
Ja bych tam uz nic dalsiho necpal. Cim mene zavislosti, tim lepe. Navic `sys_get_tmp_dir()` udela sluzbu a kdyz tam chces dat vlastni adresar, tak tam muzes dat jeho cestu.

2017-04-06 07:20 UTC, dfridrich approved these changes

2017-04-06 07:24 UTC, merged