fix person parsing from justice.cz and registration date and person t…
dfridrich/Ares pull request #21
Opened 2019-02-18 23:30 UTC by radoslavius

…ype fields added

2019-02-18 23:30 UTC, ghost requested changes
Pull request does not pass validation.

2019-02-21 10:04 UTC, ghost requested changes
Pull request does not pass validation.

2019-02-21 15:29 UTC, ghost requested changes
Pull request does not pass validation.

2019-02-21 17:53 UTC, ghost requested changes
Pull request does not pass validation.

2019-03-25 15:25 UTC, ghost requested changes
Pull request does not pass validation.

2019-03-25 15:25 UTC, ghost requested changes
Pull request does not pass validation.

2019-07-02 06:42 UTC, filipmelik commented on src/Parser/PersonParser.php
> +                    return ['name' => ucwords(mb_strtolower($name)), 'birthday' => $birthday, 'address' => isset($address) ? $address : ''];
I have found that `ucwords` does not handle words starting with diacritics properly. Let me suggest a fix I did in https://github.com/filipmelik/Ares/commit/c692788fa98cd94af4d5664f08fc3e04de8f121f (along with some code style changes)

2022-06-29 11:51 UTC, dfridrich commented
See #33

2022-06-29 11:51 UTC, closed without merging